git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
gui:
  theme:
    activeBorderColor:
      - "#80a0ff"
      - bold
    inactiveBorderColor:
      - "#626262"
    selectedLineBgColor:
      - "#1c1c1c"
    optionsTextColor:
      - "#79dac8"
    cherryPickedCommitBgColor:
      - "#262626"
    cherryPickedCommitFgColor:
      - "#80a0ff"
    unstagedChangesColor:
      - "#ff5454"
    defaultFgColor:
      - "#bdbdbd"

keybinding:
  universal:
    jumpToBlock:
      - "&"
      - "é"
      - '"'
      - "'"
      - "("
