git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
gui:
  theme:
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#6c7086"
    selectedLineBgColor:
      - "#313244"
    optionsTextColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#cba6f7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"

keybinding:
  universal:
    jumpToBlock:
      - "&"
      - "é"
      - '"'
      - "'"
      - "("
