set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g automatic-rename off
set -g status-left-length 30

# Rebind vertical split to 3 since " is used for window 3
bind 3 split-window -v

# AZERTY keyboard bindings for window navigation
bind & select-window -t 1
bind é select-window -t 2
bind '"' select-window -t 3
bind "'" select-window -t 4
bind ( select-window -t 5
bind § select-window -t 6 # Mac AZERTY
bind - select-window -t 6 # PC AZERTY
bind è select-window -t 7
bind ! select-window -t 8 # Mac AZERTY
bind _ select-window -t 8 # PC AZERTY
bind ç select-window -t 9
bind à select-window -t 10

# Color fix
set-option -sa terminal-overrides ",xterm*:Tc"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Custom Pastebin Theme (Moonfly Colors)
set -g status-style fg="#9c9c9c",bg="default"

# Left side of status bar
set -g status-left-length 100
set -g status-left "#{?client_prefix,#[fg=#80a0ff#,bg=#080808#,bold],#[fg=#080808#,bg=#80a0ff#,bold]} #S #{?client_prefix,#[fg=#080808#,bg=#1c1c1c#,nobold],#[fg=#80a0ff#,bg=#1c1c1c#,nobold]}#[fg=#9c9c9c,bg=#1c1c1c,bold] #(whoami) #{?client_prefix,#[bg=#80a0ff#,fg=#1c1c1c],#[fg=#1c1c1c#,bg=#080808]}#{?client_prefix,#[fg=#080808#,bg=#80a0ff],#[fg=#80a0ff#,bg=#080808#,bold]} #I:#P #{?client_prefix,#[fg=#80a0ff#,bg=default],#[fg=#080808#,bg=default#,nobold]}"

# Window status (middle)
set -g window-status-format "#[fg=#9c9c9c]#[bg=default]  #I:#W#F  "
set -g window-status-current-format "#[fg=#080808,bg=default]#[fg=#80a0ff,bold,bg=#080808] #I:#W#F #[fg=#080808,bg=default,nobold]"

# Right side of status bar
set -g status-right-length 100
set -g status-right "#{?client_prefix,#[fg=#80a0ff#,bg=default],#[fg=#080808#,bg=default]}#{?client_prefix,#[fg=#080808#,bg=#80a0ff#,bold],#[fg=#80a0ff#,bg=#080808,bold]} %l:%M %p #{?client_prefix,#[bg=#80a0ff#,fg=#1c1c1c],#[fg=#1c1c1c#,bg=#080808]}#[fg=#9c9c9c,bg=#1c1c1c] %d-%m-%y #{?client_prefix,#[fg=#080808#,bg=#1c1c1c#,nobold],#[fg=#80a0ff#,bg=#1c1c1c#,nobold]}#{?client_prefix,#[fg=#80a0ff#,bg=#080808#,bold],#[fg=#080808#,bg=#80a0ff#,bold]} #H "

# Window separator
set -g window-status-separator ""

# Window status alignment
set -g status-justify centre

# Pane border
set -g pane-border-style bg=default,fg="#303030"
set -g pane-active-border-style bg=default,fg="#80a0ff"

# Messages
set -g message-style bg="#1c1c1c",fg="#9c9c9c"
set -g message-command-style bg="#1c1c1c",fg="#9c9c9c"
set -g mode-style bg="#080808",fg="#80a0ff"

set-option -g status-position bottom

# Yanking
set -g @plugin 'tmux-plugins/tmux-yank'
# Vi mode for copying
set-window-option -g mode-keys vi
# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# Sessionizer
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer.sh"
