set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Enable image preview passthrough (for Yazi)
set -g allow-passthrough on

# Mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g automatic-rename off
set -g status-left-length 30

# Rebind vertical split to 3 since " is used for window 3
bind 3 split-window -v

# AZERTY keyboard bindings for window navigation
bind & select-window -t 1
bind é select-window -t 2
bind '"' select-window -t 3
bind "'" select-window -t 4
bind ( select-window -t 5
bind § select-window -t 6 # Mac AZERTY
bind - select-window -t 6 # PC AZERTY
bind è select-window -t 7
bind ! select-window -t 8 # Mac AZERTY
bind _ select-window -t 8 # PC AZERTY
bind ç select-window -t 9
bind à select-window -t 10

# Color fix
set-option -sa terminal-overrides ",xterm*:Tc"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Custom Pastebin Theme (Mocha Colors)
set -g status-style fg="#cdd6f4",bg="default"

# Left side of status bar
set -g status-left-length 100
set -g status-left "#{?client_prefix,#[fg=#cba6f7#,bg=#1e1e2e#,bold],#[fg=#11111b#,bg=#cba6f7#,bold]} #S #{?client_prefix,#[fg=#1e1e2e#,bg=#313244#,nobold],#[fg=#cba6f7#,bg=#313244#,nobold]}#[fg=#cdd6f4,bg=#313244,bold] #(whoami) #{?client_prefix,#[bg=#cba6f7#,fg=#313244],#[fg=#313244#,bg=#1e1e2e]}#{?client_prefix,#[fg=#11111b#,bg=#cba6f7],#[fg=#cba6f7#,bg=#1e1e2e#,bold]} #I:#P #{?client_prefix,#[fg=#cba6f7#,bg=default],#[fg=#1e1e2e#,bg=default#,nobold]}"

# Window status (middle)
set -g window-status-format "#[fg=#cdd6f4]#[bg=default]  #I:#W#F  "
set -g window-status-current-format "#[fg=#1e1e2e,bg=default]#[fg=#cba6f7,bold,bg=#1e1e2e] #I:#W#F #[fg=#1e1e2e,bg=default,nobold]"

# Right side of status bar
set -g status-right-length 100
set -g status-right "#{?client_prefix,#[fg=#cba6f7#,bg=default],#[fg=#1e1e2e#,bg=default]}#{?client_prefix,#[fg=#11111b#,bg=#cba6f7#,bold],#[fg=#cba6f7#,bg=#1e1e2e,bold]} %l:%M %p #{?client_prefix,#[bg=#cba6f7#,fg=#313244],#[fg=#313244#,bg=#1e1e2e]}#[fg=#cdd6f4,bg=#313244] %d-%m-%y #{?client_prefix,#[fg=#1e1e2e#,bg=#313244#,nobold],#[fg=#cba6f7#,bg=#313244#,nobold]}#{?client_prefix,#[fg=#cba6f7#,bg=#1e1e2e#,bold],#[fg=#11111b#,bg=#cba6f7#,bold]} #H "

# Window separator
set -g window-status-separator ""

# Window status alignment
set -g status-justify centre

# Pane border
set -g pane-border-style bg=default,fg="#313244"
set -g pane-active-border-style bg=default,fg="#cba6f7"

# Messages
set -g message-style bg="#1e1e2e",fg="#cba6f7"
set -g message-command-style bg="#1e1e2e",fg="#cba6f7"
set -g mode-style bg="#1e1e2e",fg="#cba6f7"

set-option -g status-position bottom

# Yanking
set -g @plugin 'tmux-plugins/tmux-yank'
# Vi mode for copying
set-window-option -g mode-keys vi
# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'

# Sessionizer
bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer.sh"
